#!/bin/bash

echo 'trytond-modules: sync'

echo 'fetch root'
git fetch -p
[ $? -ne 0 ] && exit 1

echo 'rebase root - 3.8'
git checkout 3.8 && git rebase origin/3.8
[ $? -ne 0 ] && exit 1

echo 'rebase root - master'
git checkout master && git rebase origin/master
[ $? -ne 0 ] && exit 1

echo 'fetch sub'
git submodule foreach 'git fetch -p'
[ $? -ne 0 ] && exit 1

echo 'rebase sub - 3.8'
git submodule foreach 'git checkout 3.8 && git rebase origin/3.8'
[ $? -ne 0 ] && exit 1

echo 'rebase sub - master'
git submodule foreach 'git checkout master && git rebase origin/master'
[ $? -ne 0 ] && exit 1

echo 'merge sub'
git submodule foreach 'git merge 3.8'
[ $? -ne 0 ] && exit 1

echo 'commit 3.8'
git checkout 3.8 && git submodule foreach 'git checkout 3.8' && git add . && git commit -m 'modules updated - 3.8'
[ $? -ne 0 ] && exit 1

echo 'commit master'
git checkout master && git submodule foreach 'git checkout master' && git add . aa git commit -m 'modules updated - master'
[ $? -ne 0 ] && exit 1

echo 'trytond-modules: sync ok'
